version: '3.4'

services:

  p4bench: # Benchmark driver machine
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: p4benchdriver
    hostname: p4bench
    command: /usr/sbin/init
    privileged: true
    entrypoint: /p4/benchmark/docker_entry_p4bench.sh
    tty: true
    networks:
      - nw_p4bench

  master: # Commit server
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: p4benchmaster
    hostname: master
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    # command: bash -c "/usr/sbin/init && /usr/sbin/sshd -D"
    privileged: true
    # entrypoint: /usr/sbin/sshd && /p4/benchmark/docker_entry_master.sh
    tty: true
    networks:
      nw_p4bench:
        aliases:
          - perforce

  client1: # client machine
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: p4bench
    hostname: client1
    command: /usr/sbin/init
    privileged: true
    networks:
      - nw_p4bench
    tty: true
    depends_on:
      - master

  client2: # client machine
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: p4bench
    hostname: client2
    command: /usr/sbin/init
    privileged: true
    networks:
      - nw_p4bench
    tty: true
    depends_on:
      - master

networks:

  nw_p4bench:
    driver: bridge