- name: Transfer and execute a script to install python - valid for Rocky Linux 8
  hosts: bench_clients
  become: yes
  tasks:

    - name: install packages for development etc
      yum:
        name:
        - yum-utils

    - name: clean
      command: yum clean -y all

    - name: Add Perforce repo
      ansible.builtin.yum_repository:
        name: Perforce
        description: Perforce YUM repo
        file: perforce
        baseurl: https://package.perforce.com/yum/rhel/8/x86_64
        gpgcheck: yes
        enabled: yes

    - name: update
      command: yum update -y && dnf install -y epel-release

    - name: install python 3.8
      dnf:
        name:
        - python38
        - python38-pip
        - python38-devel
        - perforce-p4python3-python3.8
        state: present

    - file:
        src: /usr/bin/python3.8
        dest: /usr/bin/python3
        mode: 0755
        state: link

      # Make sure pip3 picks up correct version of python in case of others installed.
    - file:
        src: /usr/bin/pip3.8
        dest: /usr/bin/pip3
        mode: 0755
        state: link

    - name: Pip install packages for Locust and benchmark tools
      command: pip3 install --user pyaml numpy pyzmq locust mimesis yq
      become_user: perforce

