- name: Tidy up after p4benchmark scripts
  hosts: bench_clients
  remote_user: '{{ remote_user }}'
  vars:
    remove_workspaces_per_client: "{{ lookup('env', 'REMOVE_WORKSPACES_PER_CLIENT') }}"
  tasks:

  - name: Kill locust processes if they exist
    shell: pkill --full 'locust' || true
    ignore_errors: yes

  - name: Remove base directory which has client workspaces
    file:
      path: "{{workspace_common_dir}}"
      state: absent
    when: remove_workspaces_per_client is defined and remove_workspaces_per_client == "true"

