- name: Install p4benchmark scripts prior to running benchmark
  hosts: bench_clients
  remote_user: '{{ remote_user }}'
  tasks:

    - name: Ensures directory exists
      file: path={{bench_dir}} state=directory

    - name: Copy relevant files to client machines
      copy:
        src: "{{item}}"
        dest: "{{bench_dir}}"
      with_fileglob:
        - "{{bench_dir}}/locust_files/*.py"
        - "{{bench_dir}}/utils/run_locust_worker.sh"
        - "{{bench_dir}}/bench_p4config.txt"
        - "{{bench_dir}}/{{ lookup('env', 'ANSIBLE_HOSTS') }}"

    - name: Create a directory for all perforce workspaces
      file:
        path: "{{workspace_common_dir}}"
        state: directory
        owner: perforce
      become: true
